// <auto-generated />
namespace WebBanSon.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class upDTB : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(upDTB));
        
        string IMigrationMetadata.Id
        {
            get { return "202412271652406_upDTB"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
